NAME: 'batchnorm_1x1conv'
NOTE: ''


RESUME: False

PRE_PROCESSING:
    LABEL: 'fine'

TRAIN:
    EPOCHS: 100
    BATCH_SIZE: 64
    INIT_LR: 1.e-4
    MOMENTUM: 0.9
    TRAIN_PATIENCE: 20
    OPTIM: 'adam'
    WEIGHT_DECAY: 0.
    IS_TRAIN: True

TEST:
    NUM: 0

MODEL:



