NAME: 'test'
NOTE: 'test'


RESUME: False

PRE_PROCESSING:
    LABEL: 'fine and coarse'

MODEL:
    TYPE: 'VGG16'
<<<<<<< HEAD
=======
    PRETRAINED: False
>>>>>>> 7d6ce3e92570b0c7d827397816080819045ba900
    HIDDEN: 256
    DROPOUT: 0.5
    NEURON_ARR: [32,64,128,128]

TRAIN:
    IS_TRAIN: True
<<<<<<< HEAD
    EPOCHS: 10
=======
    EPOCHS: 5
>>>>>>> 7d6ce3e92570b0c7d827397816080819045ba900
    BATCH_SIZE: 16
    INIT_LR: 1.e-1
    MOMENTUM: 0.9
    TRAIN_PATIENCE: 20
    OPTIM: 'adam'
    WEIGHT_DECAY: 0.
    NUM: 100
    VALID: 0.1
    LOSS: "categorical_crossentropy"
    VALID_FREQ: 1

TEST:
    NUM: 0
    





