NAME: 'tester'
NOTE: 'test'


RESUME: False

PRE_PROCESSING:
    LABEL: 'fine and coarse'

MODEL:
    TYPE: 'VGG16'
    PRETRAINED: True
    HIDDEN: [2048,2048]
    DROPOUT: 0.5
    NEURON_ARR: [32,64,128,128]
    VGG16_top: False


TRAIN:
    IS_TRAIN: True

    EPOCHS: 10
    BATCH_SIZE: 16
    INIT_LR: 1.e-1
    MOMENTUM: 0.9
    TRAIN_PATIENCE: 20
    OPTIM: 'adam'
    WEIGHT_DECAY: 0.
    NUM: 1000
    VALID: 0.1
    LOSS: "categorical_crossentropy"
    VALID_FREQ: 1

TEST:
    NUM: 0
    





