NAME: 'tester'
NOTE: 'test'


RESUME: False

PRE_PROCESSING:
    LABEL: 'fine'

MODEL:
    TYPE: 'from_scratch'
    PRETRAINED: True
    HIDDEN: [2048,2048]
    DROPOUT: 0.5
    NEURON_ARR: [32,64,128,128]
    VGG16_top: False
    USE_GEN: False


TRAIN:
    IS_TRAIN: True

    EPOCHS: 5
    BATCH_SIZE: 16
    INIT_LR: 3.e-2
    MOMENTUM: 0.9
    TRAIN_PATIENCE: 10
    OPTIM: 'adam'
    WEIGHT_DECAY: 0.
    NUM: 100
    VALID: 0.1
    LOSS: "categorical_crossentropy"
    VALID_FREQ: 1

TEST:
    NUM: 0
    





