NAME: 'low_lr'
NOTE: 'This run has a low learning rate'


RESUME: False

PRE_PROCESSING:
    LABEL: 'fine'

MODEL:
    TYPE: 'VGG16'
    HIDDEN: 1024
    DROPOUT: 0.5

TRAIN:
    IS_TRAIN: True
    EPOCHS: 200
    BATCH_SIZE: 64
    INIT_LR: 1.e-2
    MOMENTUM: 0.9
    TRAIN_PATIENCE: 20
    OPTIM: 'adam'
    WEIGHT_DECAY: 0.
    NUM: 0
    VALID: 0.1
    VALID_FREQ: 1
    LOSS: "categorical_crossentropy"

TEST:
    NUM: 100
    LOAD_PATH: 'my_model'





