NAME: 'VGG16_pretrained'
NOTE: 'original architecture with fine label, two FC with DO '


RESUME: False

PRE_PROCESSING:
    LABEL: 'fine'

MODEL:
    TYPE: 'VGG16'
    PRETRAINED: True
    HIDDEN: [2048,1024]
    DROPOUT_ARR: [1,0]
    DROPOUT: 0.5
    NEURON_ARR: [32,64,128,128]
    VGG16_top: False


TRAIN:
    IS_TRAIN: True
    EPOCHS: 500
    BATCH_SIZE: 64
    INIT_LR: 3.e-2
    MOMENTUM: 0.9
    TRAIN_PATIENCE: 50
    OPTIM: 'adam'
    WEIGHT_DECAY: 0.
    NUM: 0
    VALID: 0.1
    VALID_FREQ: 1
    LOSS: "categorical_crossentropy"

TEST:
    NUM: 100
    LOAD_PATH: 'my_model'