NAME: 'less_layers #08'
NOTE: 'less lr '


RESUME: False

PRE_PROCESSING:
    LABEL: 'fine'

MODEL:
    TYPE: 'from_scratch'
    HIDDEN: 256
    DROPOUT: 0.4

TRAIN:
    IS_TRAIN: True
    EPOCHS: 500
    BATCH_SIZE: 32
    INIT_LR: 3.e-2
    MOMENTUM: 0.9
    TRAIN_PATIENCE: 50
    OPTIM: 'adam'
    WEIGHT_DECAY: 0.
    NUM: 0
    VALID: 0.1
    VALID_FREQ: 1
    LOSS: "categorical_crossentropy"

TEST:
    NUM: 100
    LOAD_PATH: 'my_model'
